api_base: "/v1"
deployment_config:
  - deployment_name: "gpt-4o"
    endpoint: "https://openai-east-us2.openai.azure.com/"
    api_key: "a5d318a9bfb54f42a45ebd36fda573e0"
    api_version: "2023-05-15"
    model_name: "0"

  - deployment_name: "gpt-4o"
    endpoint: "https://openai-east-us2.openai.azure.com/"
    api_key: "646c63ae3c634308bad0d2e16d46b5f3"
    api_version: "2023-05-15"
    model_name: "1"

  - deployment_name: "gpt-4o"
    endpoint: "https://m-openai-us-east.openai.azure.com/"
    api_key: "e8f28d9241d0446cae443f0fd7e82c3e"
    api_version: "2023-05-15"
    model_name: "2"

  - deployment_name: "gpt-4o"
    endpoint: "https://m-openai-us-east.openai.azure.com/"
    api_key: "96ba469413424aeebf4a1ab43237e4a2"
    api_version: "2023-05-15"
    model_name: "3" 

  - deployment_name: "gpt-4o"
    endpoint: "https://m-openai-us-northcentral.openai.azure.com/"
    api_key: "94948b48e5ff422394815bf10cc916c3"
    api_version: "2023-05-15"
    model_name: "4"

  - deployment_name: "gpt-4o"
    endpoint: "https://m-openai-us-northcentral.openai.azure.com/"
    api_key: "edd2d97faf6c467b9a5d388f7172b7df"
    api_version: "2023-05-15"
    model_name: "5" 

  - deployment_name: "gpt-4o"
    endpoint: "https://m-openai-us-southcentral.openai.azure.com/"
    api_key: "d946328228454080907914f4478395ee"
    api_version: "2023-05-15"
    model_name: "6"

  - deployment_name: "gpt-4o"
    endpoint: "https://m-openai-us-southcentral.openai.azure.com/"
    api_key: "2a5d8517edf94f3f905db4e611c006dd"
    api_version: "2023-05-15"
    model_name: "7" 
  
  - deployment_name: "gpt-4o"
    endpoint: "https://m-openai-us-west.openai.azure.com/"
    api_key: "30a617cb0b834396aa9efb9a80262bf6"
    api_version: "2023-05-15"
    model_name: "8"

  - deployment_name: "gpt-4o"
    endpoint: "https://m-openai-us-west.openai.azure.com/"
    api_key: "7b871411cbc44a3b80086188ad125019"
    api_version: "2023-05-15"
    model_name: "9" 

  - deployment_name: "gpt-4o"
    endpoint: "https://m-openai-us-west3.openai.azure.com/"
    api_key: "704c422c489a43e4a38441772232d416"
    api_version: "2023-05-15"
    model_name: "8"

  - deployment_name: "gpt-4o"
    endpoint: "https://m-openai-us-west3.openai.azure.com/"
    api_key: "3ef374c18c544f51ac0cbf7110d563e9"
    api_version: "2023-05-15"
    model_name: "9" 
